# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gke
      tier: back
  template:
    metadata:
      labels:
        app: hello-gke
        tier: back
    spec:
      containers:
      - name: back
        image: gcr.io/javiercm-gcprocks/back:latest
        ports:
          - name: http
            containerPort: 8080
        env:
          - name: PORT
            value: "8080"